// ============================================================================
// LISTA DE PAÍSES (ISO 3166-1 alpha-2)
// ============================================================================
// Usada na ficha pública de hóspede estrangeiro (passaporte), na tela de
// Fichas de Hóspedes e na exportação pra Cloudbeds — que exige o país como
// código de 2 letras (ex.: "DE" pra Alemanha), não o nome por extenso.
//
// Cada linha: [código, nome em português, nome em inglês].
// ============================================================================

const BRUTO = [
  ['AF', 'Afeganistão', 'Afghanistan'],
  ['AX', 'Ilhas Aland', 'Åland Islands'],
  ['AL', 'Albânia', 'Albania'],
  ['DZ', 'Argélia', 'Algeria'],
  ['AS', 'Samoa Americana', 'American Samoa'],
  ['AD', 'Andorra', 'Andorra'],
  ['AO', 'Angola', 'Angola'],
  ['AI', 'Anguila', 'Anguilla'],
  ['AG', 'Antígua e Barbuda', 'Antigua and Barbuda'],
  ['AR', 'Argentina', 'Argentina'],
  ['AM', 'Armênia', 'Armenia'],
  ['AW', 'Aruba', 'Aruba'],
  ['AU', 'Austrália', 'Australia'],
  ['AT', 'Áustria', 'Austria'],
  ['AZ', 'Azerbaijão', 'Azerbaijan'],
  ['BS', 'Bahamas', 'Bahamas'],
  ['BH', 'Bahrein', 'Bahrain'],
  ['BD', 'Bangladesh', 'Bangladesh'],
  ['BB', 'Barbados', 'Barbados'],
  ['BY', 'Bielorrússia', 'Belarus'],
  ['BE', 'Bélgica', 'Belgium'],
  ['BZ', 'Belize', 'Belize'],
  ['BJ', 'Benin', 'Benin'],
  ['BM', 'Bermudas', 'Bermuda'],
  ['BT', 'Butão', 'Bhutan'],
  ['BO', 'Bolívia', 'Bolivia'],
  ['BQ', 'Bonaire, Santo Eustáquio e Saba', 'Bonaire, Sint Eustatius and Saba'],
  ['BA', 'Bósnia e Herzegovina', 'Bosnia and Herzegovina'],
  ['BW', 'Botsuana', 'Botswana'],
  ['BR', 'Brasil', 'Brazil'],
  ['VG', 'Ilhas Virgens Britânicas', 'British Virgin Islands'],
  ['BN', 'Brunei', 'Brunei'],
  ['BG', 'Bulgária', 'Bulgaria'],
  ['BF', 'Burkina Faso', 'Burkina Faso'],
  ['BI', 'Burundi', 'Burundi'],
  ['CV', 'Cabo Verde', 'Cabo Verde'],
  ['KH', 'Camboja', 'Cambodia'],
  ['CM', 'Camarões', 'Cameroon'],
  ['CA', 'Canadá', 'Canada'],
  ['KY', 'Ilhas Cayman', 'Cayman Islands'],
  ['CF', 'República Centro-Africana', 'Central African Republic'],
  ['TD', 'Chade', 'Chad'],
  ['CL', 'Chile', 'Chile'],
  ['CN', 'China', 'China'],
  ['CX', 'Ilha Christmas', 'Christmas Island'],
  ['CC', 'Ilhas Cocos', 'Cocos (Keeling) Islands'],
  ['CO', 'Colômbia', 'Colombia'],
  ['KM', 'Comores', 'Comoros'],
  ['CG', 'Congo', 'Congo'],
  ['CD', 'República Democrática do Congo', 'Congo (Democratic Republic)'],
  ['CK', 'Ilhas Cook', 'Cook Islands'],
  ['CR', 'Costa Rica', 'Costa Rica'],
  ['CI', 'Costa do Marfim', "Côte d'Ivoire"],
  ['HR', 'Croácia', 'Croatia'],
  ['CU', 'Cuba', 'Cuba'],
  ['CW', 'Curaçao', 'Curaçao'],
  ['CY', 'Chipre', 'Cyprus'],
  ['CZ', 'República Tcheca', 'Czechia'],
  ['DK', 'Dinamarca', 'Denmark'],
  ['DJ', 'Djibuti', 'Djibouti'],
  ['DM', 'Dominica', 'Dominica'],
  ['DO', 'República Dominicana', 'Dominican Republic'],
  ['EC', 'Equador', 'Ecuador'],
  ['EG', 'Egito', 'Egypt'],
  ['SV', 'El Salvador', 'El Salvador'],
  ['GQ', 'Guiné Equatorial', 'Equatorial Guinea'],
  ['ER', 'Eritreia', 'Eritrea'],
  ['EE', 'Estônia', 'Estonia'],
  ['SZ', 'Essuatíni', 'Eswatini'],
  ['ET', 'Etiópia', 'Ethiopia'],
  ['FK', 'Ilhas Malvinas', 'Falkland Islands'],
  ['FO', 'Ilhas Faroé', 'Faroe Islands'],
  ['FJ', 'Fiji', 'Fiji'],
  ['FI', 'Finlândia', 'Finland'],
  ['FR', 'França', 'France'],
  ['GF', 'Guiana Francesa', 'French Guiana'],
  ['PF', 'Polinésia Francesa', 'French Polynesia'],
  ['GA', 'Gabão', 'Gabon'],
  ['GM', 'Gâmbia', 'Gambia'],
  ['GE', 'Geórgia', 'Georgia'],
  ['DE', 'Alemanha', 'Germany'],
  ['GH', 'Gana', 'Ghana'],
  ['GI', 'Gibraltar', 'Gibraltar'],
  ['GR', 'Grécia', 'Greece'],
  ['GL', 'Groenlândia', 'Greenland'],
  ['GD', 'Granada', 'Grenada'],
  ['GP', 'Guadalupe', 'Guadeloupe'],
  ['GU', 'Guam', 'Guam'],
  ['GT', 'Guatemala', 'Guatemala'],
  ['GG', 'Guernsey', 'Guernsey'],
  ['GN', 'Guiné', 'Guinea'],
  ['GW', 'Guiné-Bissau', 'Guinea-Bissau'],
  ['GY', 'Guiana', 'Guyana'],
  ['HT', 'Haiti', 'Haiti'],
  ['VA', 'Vaticano', 'Holy See (Vatican City)'],
  ['HN', 'Honduras', 'Honduras'],
  ['HK', 'Hong Kong', 'Hong Kong'],
  ['HU', 'Hungria', 'Hungary'],
  ['IS', 'Islândia', 'Iceland'],
  ['IN', 'Índia', 'India'],
  ['ID', 'Indonésia', 'Indonesia'],
  ['IR', 'Irã', 'Iran'],
  ['IQ', 'Iraque', 'Iraq'],
  ['IE', 'Irlanda', 'Ireland'],
  ['IM', 'Ilha de Man', 'Isle of Man'],
  ['IL', 'Israel', 'Israel'],
  ['IT', 'Itália', 'Italy'],
  ['JM', 'Jamaica', 'Jamaica'],
  ['JP', 'Japão', 'Japan'],
  ['JE', 'Jersey', 'Jersey'],
  ['JO', 'Jordânia', 'Jordan'],
  ['KZ', 'Cazaquistão', 'Kazakhstan'],
  ['KE', 'Quênia', 'Kenya'],
  ['KI', 'Quiribati', 'Kiribati'],
  ['KP', 'Coreia do Norte', 'North Korea'],
  ['KR', 'Coreia do Sul', 'South Korea'],
  ['KW', 'Kuwait', 'Kuwait'],
  ['KG', 'Quirguistão', 'Kyrgyzstan'],
  ['LA', 'Laos', 'Laos'],
  ['LV', 'Letônia', 'Latvia'],
  ['LB', 'Líbano', 'Lebanon'],
  ['LS', 'Lesoto', 'Lesotho'],
  ['LR', 'Libéria', 'Liberia'],
  ['LY', 'Líbia', 'Libya'],
  ['LI', 'Liechtenstein', 'Liechtenstein'],
  ['LT', 'Lituânia', 'Lithuania'],
  ['LU', 'Luxemburgo', 'Luxembourg'],
  ['MO', 'Macau', 'Macao'],
  ['MG', 'Madagascar', 'Madagascar'],
  ['MW', 'Malawi', 'Malawi'],
  ['MY', 'Malásia', 'Malaysia'],
  ['MV', 'Maldivas', 'Maldives'],
  ['ML', 'Mali', 'Mali'],
  ['MT', 'Malta', 'Malta'],
  ['MH', 'Ilhas Marshall', 'Marshall Islands'],
  ['MQ', 'Martinica', 'Martinique'],
  ['MR', 'Mauritânia', 'Mauritania'],
  ['MU', 'Maurício', 'Mauritius'],
  ['YT', 'Mayotte', 'Mayotte'],
  ['MX', 'México', 'Mexico'],
  ['FM', 'Micronésia', 'Micronesia'],
  ['MD', 'Moldávia', 'Moldova'],
  ['MC', 'Mônaco', 'Monaco'],
  ['MN', 'Mongólia', 'Mongolia'],
  ['ME', 'Montenegro', 'Montenegro'],
  ['MS', 'Montserrat', 'Montserrat'],
  ['MA', 'Marrocos', 'Morocco'],
  ['MZ', 'Moçambique', 'Mozambique'],
  ['MM', 'Mianmar', 'Myanmar'],
  ['NA', 'Namíbia', 'Namibia'],
  ['NR', 'Nauru', 'Nauru'],
  ['NP', 'Nepal', 'Nepal'],
  ['NL', 'Países Baixos', 'Netherlands'],
  ['NC', 'Nova Caledônia', 'New Caledonia'],
  ['NZ', 'Nova Zelândia', 'New Zealand'],
  ['NI', 'Nicarágua', 'Nicaragua'],
  ['NE', 'Níger', 'Niger'],
  ['NG', 'Nigéria', 'Nigeria'],
  ['NU', 'Niue', 'Niue'],
  ['NF', 'Ilha Norfolk', 'Norfolk Island'],
  ['MK', 'Macedônia do Norte', 'North Macedonia'],
  ['MP', 'Ilhas Marianas do Norte', 'Northern Mariana Islands'],
  ['NO', 'Noruega', 'Norway'],
  ['OM', 'Omã', 'Oman'],
  ['PK', 'Paquistão', 'Pakistan'],
  ['PW', 'Palau', 'Palau'],
  ['PS', 'Palestina', 'Palestine'],
  ['PA', 'Panamá', 'Panama'],
  ['PG', 'Papua-Nova Guiné', 'Papua New Guinea'],
  ['PY', 'Paraguai', 'Paraguay'],
  ['PE', 'Peru', 'Peru'],
  ['PH', 'Filipinas', 'Philippines'],
  ['PN', 'Ilhas Pitcairn', 'Pitcairn Islands'],
  ['PL', 'Polônia', 'Poland'],
  ['PT', 'Portugal', 'Portugal'],
  ['PR', 'Porto Rico', 'Puerto Rico'],
  ['QA', 'Catar', 'Qatar'],
  ['RE', 'Reunião', 'Réunion'],
  ['RO', 'Romênia', 'Romania'],
  ['RU', 'Rússia', 'Russia'],
  ['RW', 'Ruanda', 'Rwanda'],
  ['BL', 'São Bartolomeu', 'Saint Barthélemy'],
  ['SH', 'Santa Helena', 'Saint Helena'],
  ['KN', 'São Cristóvão e Névis', 'Saint Kitts and Nevis'],
  ['LC', 'Santa Lúcia', 'Saint Lucia'],
  ['MF', 'São Martinho (França)', 'Saint Martin (French part)'],
  ['PM', 'Saint-Pierre e Miquelon', 'Saint Pierre and Miquelon'],
  ['VC', 'São Vicente e Granadinas', 'Saint Vincent and the Grenadines'],
  ['WS', 'Samoa', 'Samoa'],
  ['SM', 'San Marino', 'San Marino'],
  ['ST', 'São Tomé e Príncipe', 'Sao Tome and Principe'],
  ['SA', 'Arábia Saudita', 'Saudi Arabia'],
  ['SN', 'Senegal', 'Senegal'],
  ['RS', 'Sérvia', 'Serbia'],
  ['SC', 'Seicheles', 'Seychelles'],
  ['SL', 'Serra Leoa', 'Sierra Leone'],
  ['SG', 'Singapura', 'Singapore'],
  ['SX', 'São Martinho (Países Baixos)', 'Sint Maarten (Dutch part)'],
  ['SK', 'Eslováquia', 'Slovakia'],
  ['SI', 'Eslovênia', 'Slovenia'],
  ['SB', 'Ilhas Salomão', 'Solomon Islands'],
  ['SO', 'Somália', 'Somalia'],
  ['ZA', 'África do Sul', 'South Africa'],
  ['SS', 'Sudão do Sul', 'South Sudan'],
  ['ES', 'Espanha', 'Spain'],
  ['LK', 'Sri Lanka', 'Sri Lanka'],
  ['SD', 'Sudão', 'Sudan'],
  ['SR', 'Suriname', 'Suriname'],
  ['SJ', 'Svalbard e Jan Mayen', 'Svalbard and Jan Mayen'],
  ['SE', 'Suécia', 'Sweden'],
  ['CH', 'Suíça', 'Switzerland'],
  ['SY', 'Síria', 'Syria'],
  ['TW', 'Taiwan', 'Taiwan'],
  ['TJ', 'Tadjiquistão', 'Tajikistan'],
  ['TZ', 'Tanzânia', 'Tanzania'],
  ['TH', 'Tailândia', 'Thailand'],
  ['TL', 'Timor-Leste', 'Timor-Leste'],
  ['TG', 'Togo', 'Togo'],
  ['TK', 'Tokelau', 'Tokelau'],
  ['TO', 'Tonga', 'Tonga'],
  ['TT', 'Trinidad e Tobago', 'Trinidad and Tobago'],
  ['TN', 'Tunísia', 'Tunisia'],
  ['TR', 'Turquia', 'Türkiye'],
  ['TM', 'Turcomenistão', 'Turkmenistan'],
  ['TC', 'Ilhas Turks e Caicos', 'Turks and Caicos Islands'],
  ['TV', 'Tuvalu', 'Tuvalu'],
  ['UG', 'Uganda', 'Uganda'],
  ['UA', 'Ucrânia', 'Ukraine'],
  ['AE', 'Emirados Árabes Unidos', 'United Arab Emirates'],
  ['GB', 'Reino Unido', 'United Kingdom'],
  ['US', 'Estados Unidos', 'United States'],
  ['VI', 'Ilhas Virgens Americanas', 'U.S. Virgin Islands'],
  ['UY', 'Uruguai', 'Uruguay'],
  ['UZ', 'Uzbequistão', 'Uzbekistan'],
  ['VU', 'Vanuatu', 'Vanuatu'],
  ['VE', 'Venezuela', 'Venezuela'],
  ['VN', 'Vietnã', 'Vietnam'],
  ['WF', 'Wallis e Futuna', 'Wallis and Futuna'],
  ['EH', 'Saara Ocidental', 'Western Sahara'],
  ['YE', 'Iêmen', 'Yemen'],
  ['ZM', 'Zâmbia', 'Zambia'],
  ['ZW', 'Zimbábue', 'Zimbabwe'],
];

export const PAISES = BRUTO.map(([codigo, pt, en]) => ({ codigo, pt, en }));

// Ordenada pelo nome em inglês — quem preenche a ficha de passaporte é
// estrangeiro, então é mais fácil achar "Germany" do que "Alemanha".
export const PAISES_POR_NOME_EN = [...PAISES].sort((a, b) => a.en.localeCompare(b.en, 'en'));

const MAPA_PAISES = Object.fromEntries(PAISES.map((p) => [p.codigo, p]));

export function paisValido(codigo) {
  return !!MAPA_PAISES[String(codigo || '').toUpperCase()];
}

// Código → nome em português (pra mostrar na tela e gravar nos campos de
// texto antigos). Se o código não for reconhecido, devolve o próprio valor.
export function nomePais(codigo) {
  const chave = String(codigo || '').toUpperCase();
  return MAPA_PAISES[chave]?.pt || codigo || '';
}
